# Generated by Django 4.0 on 2023-03-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('kind', models.CharField(choices=[('start', 'start'), ('incorso', 'incorso'), ('installo', 'installo'), ('annullata', 'annullata'), ('end', 'end')], default='incorso', max_length=20)),
                ('children', models.ManyToManyField(blank=True, to='perto.Status')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='perto.task')),
            ],
        ),
    ]
