# Generated by Django 4.0 on 2023-03-08 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perto', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='task',
        ),
        migrations.RemoveField(
            model_name='status',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='slots',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='perto.Slot'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='perto.status'),
        ),
    ]
