# Generated by Django 4.0 on 2023-03-08 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perto', '0003_remove_slot_task_remove_status_task_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slots',
        ),
        migrations.AddField(
            model_name='slot',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='perto.status'),
        ),
        migrations.AddField(
            model_name='slot',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='perto.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
