# Generated by Django 4.0 on 2023-03-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perto', '0005_alter_slot_options_alter_task_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=' ')),
            ],
            options={
                'verbose_name': 'Contesto',
                'verbose_name_plural': 'Contesti',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='attuale',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='impotanza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='max',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='task',
            name='min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='minuti',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priorita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='scadenza',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskRtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=' ')),
                ('kind', models.CharField(choices=[('contiene', 'contiene'), ('altro', 'altro')], default='contiene', max_length=20)),
                ('ctask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctask', to='perto.task')),
                ('ptask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ptask', to='perto.task')),
            ],
            options={
                'verbose_name': 'TaskRtask',
                'verbose_name_plural': 'TaskRtasks',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StatusRstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromStatus', to='perto.status')),
                ('toStatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toStatus', to='perto.status')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='contesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='perto.contesto'),
        ),
    ]
